### ISSUE TITLE
Tracker cookies owa_v and owa_s are not set for single level domains

### ISSUE THREAD

**Issue by msipinski** [Open-Web-Analytics/Open-Web-Analytics#869]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [ ] I have attached http headers, console/shell errors, or debug from OWA's error log file.

**OWA Version**: 1.7.7

**PHP Version**: 7.4.33

**Webserver**: Apache 2.4.54

**Browser**: Chrome 108.0.5359.125

**Description**  
Chrome refuses to set cookies with a domain attribute which consists of only one level/segment like `;domain=.localhost` or `;domain=.server01` (with a leading dot). This results in OWA treating every page visit as completely different visitor.

**How to reproduce**  
Deploy OWA on server and start using JS tracker on a website with domain consisting of only single level/segment like `localhost` or `server01`.

**Possible Solution**  
- We tested omitting a leading dot and setting a cookie with `;domain=server01` which resulted in cookie being successfully created. According to [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#write_a_new_cookie), a leading dot is no longer needed and subdomains will be included without using it. Only the following line needed to be deleted:
  https://github.com/Open-Web-Analytics/Open-Web-Analytics/blob/03425749c558bdb07863844b93434571fa589e56/modules/base/src/tracker/Tracker.js#L321-L322

- As per [MDN docs](https://developer.mozilla.org/en-US/docs/Web/API/Document/cookie#write_a_new_cookie), omitting the `domain` cookie attribute entirely could also solve this issue:
  > `;domain=domain` [...] If not specified, this defaults to the host portion of the current document location

**Additional context**

**Comment by padams** [comment]
We can't omit the domain attribute entirely because its a feature to be able to set it to different levels. I need to look into removing the dot which used to be important but maybe not so much now...

**Comment by padams** [comment]
Also what version of Chrome is doing this?

**Comment by msipinski** [comment]
> We can't omit the domain attribute entirely because its a feature to be able to set it to different levels.

If I understand it correctly, StateManager, which is the sole interface between the cookies and the rest of the tracker code, does not provide this feature and always uses `cookie_domain` option. What's stopping it from calling `Util.setCookie` without providing the domain (empty or NULL argument) or setting `cookie_domain` option to empty or NULL, so that the cookie is set without the `domain` attribute setting it implicitly to the current domain?
