### ISSUE TITLE
Unable to set custom var with tracker js

### ISSUE THREAD

**Issue by campio97** [Open-Web-Analytics/Open-Web-Analytics#873]
**Before you open an issue:**

- [ ] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [ ] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [ ] I have attached http headers, console/shell errors, or debug from OWA's error log file.

**OWA Version**: 1.7.8

**PHP Version**: 8.0

**Webserver**: Apache

**Browser**: Chrome 109.0.5414.87

**Description**  
Hello,
i added javascript tracker to all pages of my web app.
I added the username assignment to a customVar, but this is not logged.
If I look in the owa database the cv1_name and cv1_value columns are null.
You can see the OWA tracker code and some console log of the browser below.

**Possible Solution**  

**Additional context**  

**Javascript code**
> 
    <script type="text/javascript">
        //<![CDATA[
        var owa_baseUrl = 'https://analytics.myserver.it/';
        var owa_cmds = owa_cmds || [];
        owa_cmds.push(['setDebug', true]);
        owa_cmds.push(['setSiteId', 'idofmysite']);
        owa_cmds.push(['trackPageView']);
        owa_cmds.push(['trackClicks']);
        owa_cmds.push(['trackDomStream']);
        <?php if($this->session->userdata('username')) { ?>
        owa_cmds.push(['setCustomVar', 1, 'user', '<?=$this->session->userdata('username')?>', 'page']);
        <?php } ?>

        (function() {
            var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
            owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl );
            _owa.src = owa_baseUrl + 'modules/base/dist/owa.tracker.js';
            var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
        }());
        //]]>
    </script>

**Browser logs**

> cmd queue object method name setCustomVar

> Adding global properties to event: {"visitor_id":"1674035845227652015","fsts":"1674035845","dsfs":0,"last_req":"1674037439","session_id":"1674035845016261211","nps":"0","dsps":"0","cv1":"user=hcmstudiocorno"}

**Comment by campio97** [comment]
Actually i saw that the username is included in the events, but how can i include in the user?

**Comment by campio97** [comment]
There is a command that is not in the documentation which is setUserName
Using this command I can identify the user.
The problem now is that from the OWA dashboard there is no username filter

**Comment by noone-silent** [comment]
I can confirm this. setCustomVar and the including filtering doesn't work

**Comment by mdeemy** [comment]
I encountered a similar problem and attempted various solutions without success. Ultimately, I managed to resolve it, discovering that the issue was actually linked to the sequence in which we executed commands. If we push custom variables and other data after pushing all events, it won't display properly for the initial event, which is the **base.page_request** event. 
To address this, it is essential to declare the custom variables and execute setUserName immediately after calling the **setSiteId** command. 

The following is a sample code to address this issue.

`<script type="text/javascript">
        //<![CDATA[
        var owa_baseUrl = 'https://baseurl.com/';
        var owa_cmds = owa_cmds || [];
            owa_cmds.push(['setSiteId', '@siteId']);
            owa_cmds.push(['setCustomVar', 1, 'firstVar', 'value1', 'page']);
            owa_cmds.push(['setCustomVar', 2, 'secondVar', 'value2', 'page']);
            owa_cmds.push(['setCustomVar', 3, 'thirdVar', 'value3', 'page']);
             owa_cmds.push(['setUserName', 'UserEmail']);
            owa_cmds.push(['trackPageView']);
            owa_cmds.push(['trackClicks']);
            owa_cmds.push(['trackDomStream']);
            (function () {
                var _owa = document.createElement('script'); _owa.type = 'text/javascript'; _owa.async = true;
                owa_baseUrl = ('https:' == document.location.protocol ? window.owa_baseSecUrl || owa_baseUrl.replace(/http:/, 'https:') : owa_baseUrl);
                _owa.src = owa_baseUrl + 'modules/base/dist/owa.tracker.js';
                var _owa_s = document.getElementsByTagName('script')[0]; _owa_s.parentNode.insertBefore(_owa, _owa_s);
            }());
//]]>
</script>`

I hope this will help.
