### ISSUE TITLE
Tracker reporting incorrectly for sites with the same domain

### ISSUE THREAD

**Issue by msipinski** [Open-Web-Analytics/Open-Web-Analytics#874]
**Before you open an issue:**

- [x] I followed the [installation](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Installation) or [update](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Updating) guide
- [x] [I read the troubleshooting guide in the wiki](https://github.com/Open-Web-Analytics/Open-Web-Analytics/wiki/Troubleshooting) 
- [ ] I have attached http headers, console/shell errors, or debug from OWA's error log file.

**OWA Version**: 1.7.7

**PHP Version**: 7.4.33

**Webserver**: Apache 2.4.54

**Browser**: Chrome 109.0.5414.120

**Description**  
Consider an application server like IIS, Apache or Nginx with multiple applications hosted on the same domain. Let's call these apps A and B. Their pages' paths will be then https://domain/A/**/* and https://domain/B/**/* respectively. I want to track visits on these apps separately since they serve different purposes.

If user for the first time visits tracked site/app A his visits are being reported properly, but if he then visits tracked site/app B (also for the first time) his visits are still being reported for site A incorrectly, despite the completely different Site IDs generated from OWA server and placed in JS trackers for these sites. It is especially apparent with Page Paths from site B being listed in reports for site A.

It works the same way if new visitor first visits site B nad then A: visits from both B and A will be listed only in reports for site B.

**How to reproduce**  
1. Deploy and install OWA server.
2. Add two sites A and B to generate two different Site IDs.
3. Add tracker code with different Site IDs to sites A and B with the same domain (e.g. hosted on the same server).
4. As a new visitor, visit site A (or B) to generate tracker cookies and then visit site B (or A) to generate incorrect reports.
5. Go to OWA reports page for site A to see Page Paths for site B. There should be no visits reported for the site B (unless someone visited B without visiting A beforehand).

**Possible Solution**  
Problem seems to be related to sites being able to access (and modify) the same tracker cookies and information within them.

I don't have many ideas, but how about doing some name mangling using the site ID, for example by adding site id to the cookie name (store name in StateManager) so that different sites don't interfere with each other?

**Additional context**  
Tried doing some troubleshooting myself and noticed that in the database `owa_request.site_id` does not match `owa_session.site_id` when joined on `owa_request.session_id = owa_session.id` for these incorrectly reported page visits. In `owa_request.site_id` is stored the real site id.

**Comment by criterion9** [comment]
You would likely have similar issues with other analytics providers. I would suggest utilizing subdomains (appa.domain, appb.domain) so cookies for each application can be properly aligned to your expected results.
